# Generated by Django 5.1.2 on 2024-10-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clima', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=50)),
                ('dia', models.DateField()),
                ('descricao_temp', models.CharField(max_length=255)),
                ('temp_min', models.CharField(max_length=50)),
                ('temp_max', models.CharField(max_length=50)),
            ],
        ),
    ]
